BUCKET_NAME:
CONTAINER_IMAGE:
DATABASE_NAME:
DB_NAME:
DB_PASS:
DB_USER: 
GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:
INSTANCE_NAME:
PROJECT_ID:
REGION:
SERVICE_ACCOUNT_FILE:
SUPERUSER_EMAIL:
SUPERUSER_USERNAME: