version: '3.8'

services:
  core-backend:
    build:
      context: .
      dockerfile: core/Dockerfile
    volumes:
      - ./core/backend:/app/backend
      - ./core/frontend:/app/frontend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - CLIENT_SECRETS_FILE=/app/client_secret.json
      - PYTHONPATH=/app/backend:/app/frontend
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: