# Use Node.js 16 runtime as a parent image
FROM node:16 AS build

# Set the working directory
WORKDIR /app
COPY core/frontend/package*.json /app/

# Install dependencies with legacy peer deps
RUN npm install --legacy-peer-deps

COPY core/frontend /app/

# Build the application
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=8080

# Expose the port for the application
EXPOSE 8080

# Start Nginx server
# CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "start"]